name: Phoenix
version: ${git.branch}-${git.commit.id.abbrev}
author: BlazingTide
main: me.blazingtide.phoenix.PhoenixPlugin

api-version: 1.13

libraries:
  - "org.jetbrains.kotlin:kotlin-stdlib:1.7.20"