name: Maven Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'corretto'
          java-version: '21'
      - run: java -version
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - run: mvn --batch-mode --update-snapshots verify
      - uses: actions/upload-artifact@v3
        with:
          name: Phoenix
          path: target
